export const TYPES = {
  BOOLEAN: 'boolean',
  NULL: 'null',
  UNDEFINED: 'undefined',
  NUMBER: 'number',
  STRING: 'string',
  OBJECT: 'object',
  ARRAY: 'array',
  ARRAY_BUFFER: 'arraybuffer',
  DATA_VIEW: 'dataview',
  DATE: 'date',
  ERROR: 'error',
  ARGUMENTS: 'arguments',
  COLLECTION: 'collection',
  FUNCTION: 'function',
  ELEMENT: 'element',
  TEXT: 'text',
  REGEXP: 'regexp',
  SYMBOL: 'symbol',
  SET: 'set',
  WEAK_SET: 'weakset',
  MAP: 'map',
  WEAK_MAP: 'weakmap',
  INT8_ARRAY: 'int8array',
  UNIT8_ARRAY: 'uint8array',
  UNIT8_CLAMPED_ARRAY: 'uint8clampedarray',
  INT16_ARRAY: 'int16array',
  UNIT16_ARRAY: 'uint16array',
  INT32_ARRAY: 'int32array',
  UNIT32_ARRAY: 'uint32array',
  FLOAT32_ARRAY: 'float32array',
  FLOAT64_ARRAY: 'float64array'
}

export const OBJECTS = {
  STRING: '[object String]',
  NUMBER: '[object Number]',
  BOOLEAN: '[object Boolean]',
  NULL: '[object Null]',
  UNDEFINED: '[object Undefined]',
  OBJECT: '[object Object]',
  ARGUMENTS: '[object Arguments]',
  ARRAY: '[object Array]',
  ARRAY_BUFFER: '[object ArrayBuffer]',
  INT8_ARRAY: '[object Int8Array]',
  UNIT8_ARRAY: '[object Uint8Array]',
  UNIT8_CLAMPED_ARRAY: '[object Uint8ClampedArray]',
  INT16_ARRAY: '[object Int16Array]',
  UNIT16_ARRAY: '[object Uint16Array]',
  INT32_ARRAY: '[object Int32Array]',
  UNIT32_ARRAY: '[object Uint32Array]',
  FLOAT32_ARRAY: '[object Float32Array]',
  FLOAT64_ARRAY: '[object Float64Array]',
  DATA_VIEW: '[object DataView]',
  DATE: '[object Date]',
  ERROR: '[object Error]',
  FUNCTION: '[object Function]',
  REGEXP: '[object RegExp]',
  SET: '[object Set]',
  WEAK_SET: '[object WeakSet]',
  MAP: '[object Map]',
  WEAK_MAP: '[object WeakMap]',
  SYMBOL: '[object Symbol]',
  NODE_LIST: '[object NodeList]',
  TEXT_NODE: '[object Text]'
}
