// 能够识别的数据类型名称枚举值
const TYPES = {
  BOOLEAN: 'boolean',
  BIG_INT: 'bigint',
  NULL: 'null',
  UNDEFINED: 'undefined',
  NUMBER: 'number',
  STRING: 'string',
  OBJECT: 'object',
  ARRAY: 'array',
  ARRAY_BUFFER: 'arraybuffer',
  DATA_VIEW: 'dataview',
  DATE: 'date',
  ERROR: 'error',
  PROMISE: 'promise',
  ARGUMENTS: 'arguments',
  FUNCTION: 'function',
  ELEMENT: 'element',
  FRAGMENT: 'fragment',
  COLLECTION: 'collection',
  TEXT: 'text',
  REGEXP: 'regexp',
  SYMBOL: 'symbol',
  SET: 'set',
  WEAK_SET: 'weakset',
  MAP: 'map',
  WEAK_MAP: 'weakmap',
  INT8_ARRAY: 'int8array',
  UNIT8_ARRAY: 'uint8array',
  UNIT8_CLAMPED_ARRAY: 'uint8clampedarray',
  INT16_ARRAY: 'int16array',
  UNIT16_ARRAY: 'uint16array',
  INT32_ARRAY: 'int32array',
  UNIT32_ARRAY: 'uint32array',
  FLOAT32_ARRAY: 'float32array',
  FLOAT64_ARRAY: 'float64array',
  BIG_INT64_ARRAY: 'bigint64array',
  BIG_UINT64_ARRAY: 'biguint64array'
}

export default TYPES
